/* 鐎规矮绠熺�鍕摠閸ｃ劌婀撮崸锟� */

#define  FCSW_REG_BASE_ADDR                 0
#define  FCSW_REG(dev,addr)                 (dev->RegBase + addr)

#define  FCSW_REG_BASE_ADDR_CAPABILITY      0x0
#define  FCSW_REG_BASE_ADDR_FUNCTIONALITY   0x0
#define  FCSW_REG_BASE_ADDR_PORT_CONFIG(x)  (0x1000*(x+1))
#define  FCSW_REG_BASE_ADDR_PORT_STATUS(x)  (0x1000*(x+1))

#define  FCSW_REG_DEV_ID_CDR         		(FCSW_REG_BASE_ADDR_CAPABILITY+0x0)
#define  FCSW_REG_DEV_VERSION_CDR 			(FCSW_REG_BASE_ADDR_CAPABILITY+0x4)
#define  FCSW_REG_DEV_FEAT_CDR 				(FCSW_REG_BASE_ADDR_CAPABILITY+0x8)
#define  FCSW_REG_DEV_PORT_INF_CDR			(FCSW_REG_BASE_ADDR_CAPABILITY+0xC)
#define  FCSW_REG_DEV_LUT_SIZE_CDR			(FCSW_REG_BASE_ADDR_CAPABILITY+0x14)
#define  FCSW_REG_DEV_MULT_SIZE_CDR			(FCSW_REG_BASE_ADDR_CAPABILITY+0x14)
#define  FCSW_REG_DEV_TRUNK_GROUP_NUM_CDR 	(FCSW_REG_BASE_ADDR_CAPABILITY+0x18)

#define  FCSW_REG_DEV_MODE_CFG_FCR			(FCSW_REG_BASE_ADDR_FUNCTIONALITY+0x0)
#define  FCSW_REG_DEV_SYNC_MODE_FCR			(FCSW_REG_BASE_ADDR_FUNCTIONALITY+0x50)
#define  FCSW_REG_DEV_SYNC_SET0_FCR         (FCSW_REG_BASE_ADDR_FUNCTIONALITY+0x54)
#define  FCSW_REG_DEV_SYNC_SET1_FCR         (FCSW_REG_BASE_ADDR_FUNCTIONALITY+0x58)
#define  FCSW_REG_DEV_SYNC_GET0_FCR         (FCSW_REG_BASE_ADDR_FUNCTIONALITY+0x5c)
#define  FCSW_REG_DEV_SYNC_GET1_FCR         (FCSW_REG_BASE_ADDR_FUNCTIONALITY+0x60)


#define  FCSW_REG_DEV_DOMAIN_FCR			(FCSW_REG_BASE_ADDR_FUNCTIONALITY+0x8)


#define  DEV_PORT_E_D_TOV_COR(x)            (FCSW_REG_BASE_ADDR_PORT_CONFIG(x)+0x60)
#define  DEV_PORT_R_D_TOV_COR(x)            (FCSW_REG_BASE_ADDR_PORT_CONFIG(x)+0x18)
#define  FCSW_REG_DEV_MON_PORT_FCR(x) 		(FCSW_REG_BASE_ADDR_PORT_CONFIG(x)+0x24)
#define  FCSW_REG_DEV_MC_ADDR_COR(x)        (FCSW_REG_BASE_ADDR_PORT_CONFIG(x)+0x28)
#define  FCSW_REG_DEV_MC_DID_COR(x)         (FCSW_REG_BASE_ADDR_PORT_CONFIG(x)+0x2c)
#define  FCSW_REG_DEV_MC_MASK0_COR(x)		(FCSW_REG_BASE_ADDR_PORT_CONFIG(x)+0x30)
#define  FCSW_REG_DEV_MC_MASK1_COR(x)		(FCSW_REG_BASE_ADDR_PORT_CONFIG(x)+0x34)
#define  DEV_CREDIE_COR(x)                  (FCSW_REG_BASE_ADDR_PORT_CONFIG(x)+0x40)
#define  FCSW_REG_DEV_MON_MSGID_FCR(x)      FCSW_REG_DEV_MC_DID_COR(x)


#define  FCSW_REG_DEV_PORT_STR(x)			(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x0) 	
#define  FCSW_REG_DEV_PORT_RXCNT_STR(x)	    (FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x4)
#define  FCSW_REG_DEV_PORT_TXCNT_STR(x) 	(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x8)
#define  FCSW_REG_DEV_PORT_ERR(x)			(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0xc)
#define  FCSW_REG_DEV_PORT_SOF_ERR(x)		(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x10)
#define  FCSW_REG_DEV_PORT_EOF_ERR(x)		(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x14)
#define  FCSW_REG_DEV_PORT_SHORT_ERR(x)		(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x18)
#define  FCSW_REG_DEV_PORT_LONG_ERR(x)		(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x1c)
#define  FCSW_REG_DEV_PORT_CRC_ERR(x)		(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x20)
#define  FCSW_REG_DEV_PORT_DID_ERR(x)		(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x24)
#define  FCSW_REG_DEV_PORT_CODE_ERR(x)		(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x28)
#define  FCSW_REG_DEV_PORT_POLARITY_ERR(x) 	(FCSW_REG_BASE_ADDR_PORT_STATUS(x)+0x2c)



#define SW_DEVICE_ID 0xFC02
#define SW_VENDER_ID 0x4248

u32 FCSW_Reg_Read_LB(u32 addr);
void FCSW_Reg_Write_LB(u32 addr, u32 value);

u32 FCSW_Reg_Read_AXI(u32 addr);
void FCSW_Reg_Write_AXI(u32 addr, u32 value);


